### ISSUE TITLE
Blocked on "Jobs" view when there are no jobs

### ISSUE THREAD

**Issue by mehdid** [edf-hpc/slurm-web#143] opened 2016-10-20 16:10 UTC
If a user happens to pick a cluster without jobs listed, he won't be able to switch to another cluster before reloading the dashboard or changing for another view before choosing a different cluster.

**Comment by rezib** [comment] 2016-10-21 08:12
Duplicate of #136.

**Closed by rezib** 2016-10-21 08:12 UTC
Labels: bug
