### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by cdsgalaxy** [edf-hpc/slurm-web#134] opened 2016-08-25 18:24 UTC
dpkg-buildpackage -rfakeroot -D -us -uc
dpkg-buildpackage: warning: using a gain-root-command while being root
dpkg-buildpackage: source package slurm-web
dpkg-buildpackage: source version 2.1.0
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by Rémi Palancher <remi-externe.palancher@edf.fr>
 dpkg-source --before-build slurm-web-master
dpkg-buildpackage: host architecture amd64
dpkg-checkbuilddeps: Unmet build dependencies: node-opentypejs (>> 0.4.3-1)
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
debuild: fatal error at line 1364:
dpkg-buildpackage -rfakeroot -D -us -uc failed

Also, tried using the -d flag, had to make a symlink js -> dashboard/js

**Comment by rezib** [comment] 2016-08-26 06:56
Hi @cdsgalaxy,

The problem is that `node-opentypejs` is not installed. As stated in the wiki, you can download it there:
https://people.debian.org/~ana/slurmweb/

**Comment by rezib** [comment] 2016-10-18 08:15
Hey @cdsgalaxy, is that OK for you? Can we finally close this issue?

**Closed by rezib** 2016-10-18 08:15 UTC
