### ISSUE TITLE
t0 on Gantt chart shifted when client's TZ and server's TZ are different

### ISSUE THREAD

**Issue by mehdid** [edf-hpc/slurm-web#70] opened 2015-12-02 13:19 UTC
On Gantt charts, the red line representing the time=now is shifted in the past (or future, depending on the timezone) when the client's timezone and server's timezone are different. The problem should be easy to reproduce if you set your local machine's timezone to something different than Paris (We've tested with Central Time, i.e. -6h)

**Comment by rezib** [comment] 2016-01-12 15:38
Closing the issue since we're not able to reproduce it anymore.

**Closed by rezib** 2016-01-12 15:38 UTC
Labels: can't reproduce
